import {
  defaultKanbanState,
  defaultWorkspaceState,
  defaultSessionState,
  defaultSessionRuntimeState,
  defaultUIState,
  defaultGitHubState,
  defaultGitLabState,
  defaultLinearState,
  defaultSystemState,
} from "./slices";

export const defaultState = {
  workflows: defaultKanbanState.workflows,
  tasks: defaultKanbanState.tasks,
  workspaces: defaultWorkspaceState.workspaces,
  messages: defaultSessionState.messages,
  turns: defaultSessionState.turns,
  pendingModel: defaultSessionState.pendingModel,
  activeModel: defaultSessionState.activeModel,
  taskPlans: defaultSessionState.taskPlans,
  queue: defaultSessionState.queue,
  terminal: defaultSessionRuntimeState.terminal,
  shell: defaultSessionRuntimeState.shell,
  processes: defaultSessionRuntimeState.processes,
  environmentIdBySessionId: defaultSessionRuntimeState.environmentIdBySessionId,
  sessionCommits: defaultSessionRuntimeState.sessionCommits,
  contextWindow: defaultSessionRuntimeState.contextWindow,
  agents: defaultSessionRuntimeState.agents,
  availableCommands: defaultSessionRuntimeState.availableCommands,
  userShells: defaultSessionRuntimeState.userShells,
  agentCapabilities: defaultSessionRuntimeState.agentCapabilities,
  promptUsage: defaultSessionRuntimeState.promptUsage,
  pendingPrUrlByTaskId: defaultGitHubState.pendingPrUrlByTaskId,
  taskMRs: defaultGitLabState.taskMRs,
  linearIssueWatches: defaultLinearState.linearIssueWatches,
  system: defaultSystemState.system,
  previewPanel: defaultUIState.previewPanel,
  rightPanel: defaultUIState.rightPanel,
  diffs: defaultUIState.diffs,
  connection: defaultUIState.connection,
  mobileKanban: defaultUIState.mobileKanban,
  mobileSession: defaultUIState.mobileSession,
  chatInput: defaultUIState.chatInput,
  documentPanel: defaultUIState.documentPanel,
  systemHealth: defaultUIState.systemHealth,
  quickChat: defaultUIState.quickChat,
  sessionFailureNotification: defaultUIState.sessionFailureNotification,
  bottomTerminal: defaultUIState.bottomTerminal,
  sidebarViews: defaultUIState.sidebarViews,
  collapsedSubtaskParents: defaultUIState.collapsedSubtaskParents,
  kanbanPreviewedTaskId: defaultUIState.kanbanPreviewedTaskId,
  sidebarTaskPrefs: defaultUIState.sidebarTaskPrefs,
};

export type DefaultState = typeof defaultState;

export function mergeInitialState(initialState?: Partial<DefaultState>): DefaultState {
  if (!initialState) return defaultState;

  return {
    ...defaultState,
    ...initialState,
    // Ensure nested objects are properly merged
    workflows: { ...defaultState.workflows, ...initialState.workflows },
    tasks: { ...defaultState.tasks, ...initialState.tasks },
    workspaces: { ...defaultState.workspaces, ...initialState.workspaces },
    messages: { ...defaultState.messages, ...initialState.messages },
    turns: { ...defaultState.turns, ...initialState.turns },
    pendingModel: { ...defaultState.pendingModel, ...initialState.pendingModel },
    activeModel: { ...defaultState.activeModel, ...initialState.activeModel },
    taskPlans: { ...defaultState.taskPlans, ...initialState.taskPlans },
    queue: { ...defaultState.queue, ...initialState.queue },
    terminal: { ...defaultState.terminal, ...initialState.terminal },
    shell: { ...defaultState.shell, ...initialState.shell },
    processes: { ...defaultState.processes, ...initialState.processes },
    sessionCommits: { ...defaultState.sessionCommits, ...initialState.sessionCommits },
    contextWindow: { ...defaultState.contextWindow, ...initialState.contextWindow },
    agents: { ...defaultState.agents, ...initialState.agents },
    userShells: { ...defaultState.userShells, ...initialState.userShells },
    agentCapabilities: { ...defaultState.agentCapabilities, ...initialState.agentCapabilities },
    promptUsage: { ...defaultState.promptUsage, ...initialState.promptUsage },
    taskMRs: { ...defaultState.taskMRs, ...initialState.taskMRs },
    linearIssueWatches: {
      ...defaultState.linearIssueWatches,
      ...initialState.linearIssueWatches,
    },
    system: { ...defaultState.system, ...initialState.system },
    previewPanel: { ...defaultState.previewPanel, ...initialState.previewPanel },
    rightPanel: { ...defaultState.rightPanel, ...initialState.rightPanel },
    diffs: { ...defaultState.diffs, ...initialState.diffs },
    connection: { ...defaultState.connection, ...initialState.connection },
    mobileKanban: { ...defaultState.mobileKanban, ...initialState.mobileKanban },
    mobileSession: { ...defaultState.mobileSession, ...initialState.mobileSession },
    chatInput: { ...defaultState.chatInput, ...initialState.chatInput },
    documentPanel: { ...defaultState.documentPanel, ...initialState.documentPanel },
    systemHealth: { ...defaultState.systemHealth, ...initialState.systemHealth },
    quickChat: { ...defaultState.quickChat, ...initialState.quickChat },
    sessionFailureNotification:
      initialState.sessionFailureNotification ?? defaultState.sessionFailureNotification,
    bottomTerminal: { ...defaultState.bottomTerminal, ...initialState.bottomTerminal },
    sidebarViews: { ...defaultState.sidebarViews, ...initialState.sidebarViews },
    collapsedSubtaskParents:
      initialState.collapsedSubtaskParents ?? defaultState.collapsedSubtaskParents,
  };
}
