// Re-export all types from slices for backwards compatibility.
// Extracted from store.ts to keep that file under the max-lines limit.
export type {
  KanbanState,
  KanbanMultiState,
  WorkflowSnapshotData,
  WorkflowsState,
  TaskState,
  WorkspaceState,
  MessagesState,
  TurnsState,
  Worktree,
  PendingModelState,
  ActiveModelState,
  TerminalState,
  ShellState,
  ProcessStatusEntry,
  ProcessState,
  FileInfo,
  GitStatusEntry,
  ContextWindowEntry,
  ContextWindowState,
  AgentState,
  UserShellInfo,
  UserShellsState,
  PreviewStage,
  PreviewViewMode,
  PreviewDevicePreset,
  PreviewPanelState,
  RightPanelState,
  DiffState,
  ConnectionState,
  MobileKanbanState,
  GitHubSlice,
  GitHubSliceState,
  GitHubSliceActions,
  LinearSlice,
  LinearSliceState,
  LinearSliceActions,
  LinearIssueWatchesState,
} from "./slices";
