package streams

import (
	"strings"
	"time"
)

const (
	GuardedTTYAgentID           = "codex-acp"
	GuardedTTYContractVersion   = 1
	GuardedTTYExecMethod        = "command/exec"
	GuardedTTYAgentAction       = "agent.guarded_tty.exec"
	GuardedTTYMaxArgCount       = 64
	GuardedTTYMaxSingleArgBytes = 4 * 1024
	GuardedTTYMaxTotalArgBytes  = 8 * 1024
	GuardedTTYMaxOutputBytes    = 64 * 1024
	GuardedTTYDenialAppServer   = "app_server_error"
	GuardedTTYDenialCancelled   = "cancelled"
	GuardedTTYDenialInvalid     = "invalid_output"
	GuardedTTYDenialOverflow    = "output_overflow"
	GuardedTTYDenialStale       = "stale_session"
	GuardedTTYDenialTimeout     = "timeout"
)

// ValidateGuardedTTYArgv mirrors the version-one bridge limits. Keeping the
// same bounds at every trust boundary prevents a request from being accepted
// by Kandev only to be rejected deeper inside the guarded agent process.
func ValidateGuardedTTYArgv(argv []string) bool {
	if len(argv) == 0 || len(argv) > GuardedTTYMaxArgCount {
		return false
	}
	total := 0
	for _, arg := range argv {
		if arg == "" || strings.ContainsRune(arg, '\x00') || len(arg) > GuardedTTYMaxSingleArgBytes {
			return false
		}
		total += len(arg)
		if total > GuardedTTYMaxTotalArgBytes {
			return false
		}
	}
	return true
}

// GuardedTTYAgentRequest is the internal backend-to-agentctl request. Every
// identity is generated by Kandev and checked again against the agentctl
// launch configuration before the adapter receives the argv.
type GuardedTTYAgentRequest struct {
	AttestationID string   `json:"attestation_id"`
	ExecutionID   string   `json:"execution_id"`
	TaskID        string   `json:"task_id"`
	SessionID     string   `json:"session_id"`
	Argv          []string `json:"argv"`
}

// GuardedTTYBridgeRequest is the only request shape an adapter may forward to
// an agent bridge. Launch identity and the audit attestation stop at agentctl;
// the bridge receives only the active ACP session correlation and argv.
type GuardedTTYBridgeRequest struct {
	SessionID string   `json:"session_id"`
	Argv      []string `json:"argv"`
}

// GuardedTTYExecRequest carries only the model-selected argv plus the trusted
// backend execution binding. Runtime security fields are intentionally absent.
type GuardedTTYExecRequest struct {
	Execution MCPExecutionContext `json:"-"`
	Argv      []string            `json:"argv"`
}

// GuardedTTYExecReceipt is the bounded, auditable result returned by the
// negotiated codex-acp bridge. Raw environment and sandbox data are excluded.
type GuardedTTYExecReceipt struct {
	AttestationID   string    `json:"attestation_id"`
	ContractVersion int       `json:"contract_version,omitempty"`
	BridgeVersion   string    `json:"bridge_version,omitempty"`
	ExecutionID     string    `json:"execution_id"`
	TaskID          string    `json:"task_id"`
	SessionID       string    `json:"session_id"`
	ACPSessionID    string    `json:"acp_session_id,omitempty"`
	Method          string    `json:"method"`
	RequestedTTY    bool      `json:"requested_tty"`
	DispatchedTTY   bool      `json:"dispatched_tty"`
	ProcessID       string    `json:"process_id,omitempty"`
	CWD             string    `json:"cwd,omitempty"`
	Stdout          string    `json:"stdout,omitempty"`
	Stderr          string    `json:"stderr,omitempty"`
	StdoutBytes     int       `json:"stdout_bytes,omitempty"`
	StderrBytes     int       `json:"stderr_bytes,omitempty"`
	Output          string    `json:"output,omitempty"`
	OutputBytes     int       `json:"output_bytes,omitempty"`
	OutputSHA256    string    `json:"output_sha256,omitempty"`
	ExitCode        int       `json:"exit_code"`
	Outcome         string    `json:"outcome,omitempty"`
	DenialCode      string    `json:"denial_code,omitempty"`
	CompletionCount int       `json:"completion_count,omitempty"`
	StartedAt       time.Time `json:"started_at,omitempty"`
	CompletedAt     time.Time `json:"completed_at"`
}
